{
  "comments": [
    {
      "key": {
        "uuid": "415bc9da_44cc87ac",
        "filename": "rdopkg/utils/specfile.py",
        "patchSetId": 1
      },
      "lineNbr": 294,
      "author": {
        "id": 180
      },
      "writtenOn": "2019-08-20T21:35:33Z",
      "side": 1,
      "message": "If I recall correctly this had issues",
      "range": {
        "startLine": 294,
        "startChar": 38,
        "endLine": 294,
        "endChar": 54
      },
      "revId": "217a080742d3262e517309a6fa9665863d246ac7",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    }
  ]
}